#服务器端口
server:
  port: 8200

#Spring配置
spring:
  datasource:
    #主数据源信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.demo.master.url}
    username: ${blade.datasource.demo.master.username}
    password: ${blade.datasource.demo.master.password}
    #动态数据源信息
    dynamic:
      druid:
        #通用校验配置
        validation-query: select 1
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        slave:
          druid:
            #独立校验配置
            validation-query: select 1
            #oracle校验
            #validation-query: select 1 from dual
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${blade.datasource.demo.slave.url}
          username: ${blade.datasource.demo.slave.username}
          password: ${blade.datasource.demo.slave.password}
