#不分表仅分库
spring:
  #主数据源
  datasource:
    # MySql
    url: jdbc:mysql://localhost:3306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  #sharding数据源
  shardingsphere:
    datasource:
      names: ds1,ds2
      #数据库连接别名
      ds1:
        #数据连接池类型
        type: com.alibaba.druid.pool.DruidDataSource
        #驱动类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        #jdbc地址
        url: jdbc:mysql://localhost:3306/bladex1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        #数据库账号
        username: root
        #数据库密码
        password: root
      #数据库连接别名
      ds2:
        #数据连接池类型
        type: com.alibaba.druid.pool.DruidDataSource
        #驱动类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        #jdbc地址
        jdbc-url: jdbc:mysql://localhost:3306/bladex2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        #数据库账号
        username: root
        #数据库密码
        password: root
    rules:
      sharding:
        #主键生成类型
        key-generators:
          snowflake:
            type: SNOWFLAKE
        #默认分库策略
        default-database-strategy:
          standard:
            #列名
            sharding-column: id
            #算法名
            sharding-algorithm-name: database-inline
        tables:
          #表名代号
          blade_notice:
            #实际节点名称，格式为 库名$->{0..n1}.表名
            actual-data-nodes: ds$->{1..2}.blade_notice
            #主键生成策略
            key-generate-strategy:
              #主键名
              column: id
              #策略算法
              key-generator-name: snowflake
        #分库分表算法
        sharding-algorithms:
          #分库算法名
          database-inline:
            #算法类型
            type: INLINE
            props:
              #算法表达式
              #表达式写法非常自由，以下配置仅作为参考
              #ds$->{id % 2 + 1} 代表对id进行取余，根据id的基偶来指向 ds1和ds2
              algorithm-expression: ds$->{id % 2 + 1}
