export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "关联工单ID关联lijianxin_biz_work_order表id",
      prop: "orderId",
      type: "input",
    },
    {
      label: "处置描述",
      prop: "disposalDesc",
      type: "input",
      search: true,
    },
    {
      label: "处置时间",
      prop: "disposalTime",
      type: "input",
    },
    {
      label: "处置人ID维修员，关联sys_user表",
      prop: "disposalUserId",
      type: "input",
    },
    {
      label: "验收状态：0=待验收，1=验收通过，2=验收不通过",
      prop: "checkStatus",
      type: "input",
    },
    {
      label: "验收人ID调度员，关联sys_user表",
      prop: "checkUserId",
      type: "input",
    },
    {
      label: "验收时间",
      prop: "checkTime",
      type: "input",
    },
    {
      label: "验收备注",
      prop: "checkRemark",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人ID通常为维修员",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门ID",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人ID可能为验收人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
