export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  menuWidth: 300,
  column: [
    {
      label: " 主键 ",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 租户 ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 隐患描述 ",
      prop: "hiddenDangerDesc",
      type: "input",
      search: true,
    },
    {
      label: " 隐患类型",
      prop: "hiddenDangerType",
      type: "input",
      search: true,
    },
    {
      label: " 隐患严重程度",
      prop: "dangerLevel",
      type: "input",
    },
    {
      label: " 隐患位置 ",
      prop: "location",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 发现人 ",
      prop: "discoverer",
      type: "input",
    },
    {
      label: " 发现时间 ",
      prop: "discoverTime",
      type: "input",
    },
    {
      label: " 工单号 ",
      prop: "workOrderNum",
      type: "input",
    },
    {
      label: " 被分配维修人员 ID",
      prop: "assignPerson",
      type: "input",
    },
    {
      label: " 分配时间 ",
      prop: "assignTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 处置措施 ",
      prop: "handleMeasure",
      type: "input",
    },
    {
      label: " 处置结果",
      prop: "handleResult",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 处置完成时间 ",
      prop: "handleTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 隐患发现时环境条件",
      prop: "environmentInfo",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "关联设备编号",
      prop: "relatedEquipment",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "隐患现场图片URL",
      prop: "picUrl",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "审核人ID",
      prop: "reviewUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "审核时间",
      prop: "reviewTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "审核备注",
      prop: "reviewRemark",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "扩展字段1",
      prop: "extendField1",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "扩展字段2",
      prop: "extendField2",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 创建人 ",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 创建部门 ",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 创建时间 ",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 修改人 ",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 修改时间 ",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: " 是否已删除 ",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
