export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "父主键",
      prop: "parentId",
      type: "tree",
      dicData: [],
      props: {
        label: "title",
      },
      value: 0,
      span: 24,
    },
    {
      label: "部门类型",
      prop: "orgCategory",
      type: "select",
      dicUrl: "/blade-system/dict/dictionary?code=org_category",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      span: 24,
      search: true,
    },
    {
      label: "部门名",
      prop: "orgName",
      type: "input",
      search: true,
    },
    {
      label: "部门全称",
      prop: "fullName",
      type: "input",
    },
    {
      label: "排序",
      prop: "sort",
      type: "input",
      span: 24,
    },
    {
      label: "备注",
      prop: "remark",
      type: "textarea",
      span: 24,
    },
  ]
}
