server:
  port: 8301

spring:
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
    connection-timeout: 15000
    # 生产者配置
    publisher-confirm-type: correlated
    publisher-returns: true 