server:
  port: 8302

spring:
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
    connection-timeout: 15000
    # 消费者配置
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0 