<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>BladeX-Biz</artifactId>
        <groupId>org.springblade</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>blade-example</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>
    <description>BladeX 微服务范例集合</description>

    <modules>
        <module>blade-apollo</module>
        <module>blade-mqtt-broker</module>
        <module>blade-mqtt-client</module>
        <module>blade-rabbit-listener</module>
        <module>blade-rabbit-publisher</module>
        <module>blade-develop</module>
        <module>blade-seata-order</module>
        <module>blade-seata-storage</module>
        <module>blade-sharding-jdbc</module>
        <module>blade-xxl-job</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-biz-common</artifactId>
        </dependency>
    </dependencies>

</project>
